#!/usr/bin/env bash
# Worker 节点一键部署：全部从 ACR 拉取，无需业务仓 git — Author: kejiqing
#
# 项目坐标：e2bserver（公开仓 passionke/deploy-all-in-one）
#
#   curl -fsSL https://raw.githubusercontent.com/passionke/deploy-all-in-one/main/e2bserver/bootstrap-worker.sh \
#     -o bootstrap-worker.sh
#   E2B_IMAGE_TAG=release-v1.0.1 \
#   E2B_PANEL_URL='http://panel:3000' E2B_WORKER_TOKEN='...' E2B_ADVERTISE_HOST='...' \
#     bash bootstrap-worker.sh
#
# Env:
#   E2B_IMAGE_TAG        推荐：release-v1.0.1
#   E2B_PANEL_URL        必填
#   E2B_WORKER_TOKEN     必填
#   E2B_ADVERTISE_HOST   远程节点必填
#   E2B_WORKER_ADDR      默认 0.0.0.0:3100
#   E2B_MAX_SANDBOXES    默认 4
#   ACR_REGISTRY / ACR_USERNAME / ACR_PASSWORD
set -euo pipefail

RUNTIME="${E2B_CONTAINER_RUNTIME:-docker}"
export E2B_CONTAINER_RUNTIME="$RUNTIME"
INSTALL_DIR="${E2B_INSTALL_DIR:-/opt/e2b-worker}"
WORKER_ADDR="${E2B_WORKER_ADDR:-0.0.0.0:3100}"
ACR_REGISTRY="${ACR_REGISTRY:-crpi-cf9vxpq3n8or17mw.cn-hangzhou.personal.cr.aliyuncs.com/passionke}"

die() { echo "error: $*" >&2; exit 1; }

if [[ "$(uname -s)" == "Darwin" ]]; then
  die "macOS cannot use ACR Linux binary — run on a Linux Worker host"
fi

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing command: $1"
}

detect_arch_tag() {
  case "$(uname -m)" in
    x86_64) echo amd64 ;;
    aarch64|arm64) echo arm64 ;;
    *) die "unsupported arch: $(uname -m)" ;;
  esac
}

image_tag() {
  if [[ -n "${E2B_IMAGE_TAG:-}" ]]; then
    echo "$E2B_IMAGE_TAG"
  else
    detect_arch_tag
  fi
}

acr_login_if_needed() {
  local host="${ACR_REGISTRY%%/*}" user="${ACR_USERNAME:-${ACR_USER:-}}"
  if [[ -n "$user" && -n "${ACR_PASSWORD:-}" ]]; then
    echo "$ACR_PASSWORD" | "$RUNTIME" login "$host" -u "$user" --password-stdin
  fi
}

pull_and_extract() {
  local tag ref cid
  tag="$(image_tag)"
  ref="${ACR_REGISTRY%/}/e2b-binaries:${tag}"
  echo "==> pull $ref"
  acr_login_if_needed
  "$RUNTIME" pull "$ref" || die "failed to pull $ref — wait for release CI / check tag"

  mkdir -p "$INSTALL_DIR/bin" "$INSTALL_DIR/config" "$INSTALL_DIR/data"
  cid="$("$RUNTIME" create "$ref")"
  "$RUNTIME" cp "$cid:/opt/e2b/bin/e2b-worker" "$INSTALL_DIR/bin/e2b-worker"
  "$RUNTIME" rm "$cid" >/dev/null
  chmod 755 "$INSTALL_DIR/bin/e2b-worker"
  echo "==> installed $INSTALL_DIR/bin/e2b-worker"
}

pull_base() {
  local tag ref
  tag="$(image_tag)"
  ref="${ACR_REGISTRY%/}/e2b-base:${tag}"
  echo "==> pull $ref"
  acr_login_if_needed
  "$RUNTIME" pull "$ref" || die "failed to pull $ref"
  "$RUNTIME" tag "$ref" e2b-base:latest
  echo "==> e2b-base:latest ← $ref"
}

write_config() {
  [[ -n "${E2B_WORKER_TOKEN:-}" ]] || die "set E2B_WORKER_TOKEN (same as Panel cluster.worker_token)"
  [[ -n "${E2B_PANEL_URL:-}" ]] || die "set E2B_PANEL_URL (Panel API, e.g. http://10.8.0.9:3000)"

  cat >"$INSTALL_DIR/config/worker.toml" <<EOF
# generated by bootstrap-worker.sh — Author: kejiqing
# coord: e2bserver @ passionke/deploy-all-in-one
worker_token = "$E2B_WORKER_TOKEN"
panel_url = "$E2B_PANEL_URL"
worker_addr = "$WORKER_ADDR"
advertise_host = "${E2B_ADVERTISE_HOST:-}"
max_sandboxes = ${E2B_MAX_SANDBOXES:-4}
data_dir = "$INSTALL_DIR/data"
heartbeat_interval_secs = 15
container_runtime = "$RUNTIME"
health_wait_timeout_secs = 30
traffic_ports = [3000, 7681, 8080]

[nas]
server = "nfs.supone.top"
export = "/mnt/NAS0/nfs-export"
host_mount_root = "/mnt/nas0"
nfs_version = "3"
sandbox_inject = "bind"
mount_options_linux = "vers=3,nolock,rw,hard,intr"
EOF
  chmod 600 "$INSTALL_DIR/config/worker.toml"
  echo "==> config $INSTALL_DIR/config/worker.toml"
}

start_worker() {
  pkill -f "$INSTALL_DIR/bin/e2b-worker run" 2>/dev/null || true
  sleep 1
  nohup env E2B_WORKER_CONFIG="$INSTALL_DIR/config/worker.toml" \
    "$INSTALL_DIR/bin/e2b-worker" run >>"$INSTALL_DIR/e2b-worker.log" 2>&1 &
  echo "==> e2b-worker pid=$! log=$INSTALL_DIR/e2b-worker.log"
}

verify() {
  sleep 2
  local host="${WORKER_ADDR%:*}" port="${WORKER_ADDR##*:}"
  [[ "$host" == "0.0.0.0" ]] && host="127.0.0.1"
  curl -sf -H "X-Worker-Token: $E2B_WORKER_TOKEN" \
    "http://${host}:${port}/internal/v1/health" | python3 -m json.tool \
    || die "worker health check failed — see $INSTALL_DIR/e2b-worker.log"
}

main() {
  require_cmd curl
  require_cmd "$RUNTIME"
  [[ -n "${E2B_IMAGE_TAG:-}" ]] || echo "==> warning: E2B_IMAGE_TAG unset, using arch tag $(detect_arch_tag)"

  echo "==> coord: e2bserver"
  echo "==> install dir: $INSTALL_DIR"
  echo "==> image tag: $(image_tag) (ACR_REGISTRY=$ACR_REGISTRY)"

  pull_and_extract
  pull_base
  write_config
  start_worker
  verify

  echo ""
  echo "worker ready (coord e2bserver)."
  echo "  registers with Panel at $E2B_PANEL_URL"
}

main "$@"
