#!/usr/bin/env bash
# Worker 节点一键部署：全部从 ACR 拉取，无需业务仓 git — Author: kejiqing
#
# 项目坐标：e2bserver（公开仓 passionke/deploy-all-in-one）
#
# 用法：
#   # 稳定项放同目录或 cwd 的 .env（E2B_PANEL_URL / E2B_WORKER_TOKEN / E2B_ADVERTISE_HOST …）
#   bash bootstrap-worker.sh release-v1.0.1
#
# .env 示例见 .env.worker.example
#
# 版本只走命令行参数，不要用 E2B_IMAGE_TAG 环境变量当主路径。
# script-rev: 2026-07-14-cli-tag-dotenv
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

die() { echo "error: $*" >&2; exit 1; }

load_dotenv() {
  local f
  for f in "${PWD}/.env" "${SCRIPT_DIR}/.env"; do
    if [[ -f "$f" ]]; then
      set -a
      # shellcheck disable=SC1090
      source "$f"
      set +a
      echo "==> loaded $f"
      return 0
    fi
  done
}

load_dotenv

RUNTIME="${E2B_CONTAINER_RUNTIME:-docker}"
export E2B_CONTAINER_RUNTIME="$RUNTIME"
INSTALL_DIR="${E2B_INSTALL_DIR:-/opt/e2b-worker}"
WORKER_ADDR="${E2B_WORKER_ADDR:-0.0.0.0:3100}"
ACR_REGISTRY="${ACR_REGISTRY:-crpi-cf9vxpq3n8or17mw.cn-hangzhou.personal.cr.aliyuncs.com/passionke}"

if [[ "$(uname -s)" == "Darwin" ]]; then
  die "macOS cannot use ACR Linux binary — run on a Linux Worker host"
fi

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing command: $1"
}

detect_arch_tag() {
  case "$(uname -m)" in
    x86_64) echo amd64 ;;
    aarch64|arm64) echo arm64 ;;
    *) die "unsupported arch: $(uname -m)" ;;
  esac
}

# $1 = release tag（主路径）；未传则退回 arch tag
resolve_image_tag() {
  local arg="${1:-}"
  if [[ -n "$arg" ]]; then
    echo "$arg"
  else
    echo "==> warning: no tag arg, using arch $(detect_arch_tag)" >&2
    detect_arch_tag
  fi
}

acr_login_if_needed() {
  local host="${ACR_REGISTRY%%/*}" user="${ACR_USERNAME:-${ACR_USER:-}}"
  if [[ -n "$user" && -n "${ACR_PASSWORD:-}" ]]; then
    echo "$ACR_PASSWORD" | "$RUNTIME" login "$host" -u "$user" --password-stdin
  fi
}

pull_and_extract() {
  local tag="$1" ref cid
  ref="${ACR_REGISTRY%/}/e2b-binaries:${tag}"
  echo "==> pull $ref"
  acr_login_if_needed
  "$RUNTIME" pull "$ref" || die "failed to pull $ref — wait for release CI / check tag"

  mkdir -p "$INSTALL_DIR/bin" "$INSTALL_DIR/config" "$INSTALL_DIR/data"
  cid="$("$RUNTIME" create "$ref")"
  "$RUNTIME" cp "$cid:/opt/e2b/bin/e2b-worker" "$INSTALL_DIR/bin/e2b-worker"
  "$RUNTIME" rm "$cid" >/dev/null
  chmod 755 "$INSTALL_DIR/bin/e2b-worker"
  echo "==> installed $INSTALL_DIR/bin/e2b-worker"
}

pull_base() {
  local tag="$1" ref
  ref="${ACR_REGISTRY%/}/e2b-base:${tag}"
  echo "==> pull $ref"
  acr_login_if_needed
  "$RUNTIME" pull "$ref" || die "failed to pull $ref"
  "$RUNTIME" tag "$ref" e2b-base:latest
  echo "==> e2b-base:latest ← $ref"
}

write_config() {
  [[ -n "${E2B_WORKER_TOKEN:-}" ]] || die "set E2B_WORKER_TOKEN in .env (same as Panel cluster.worker_token)"
  [[ -n "${E2B_PANEL_URL:-}" ]] || die "set E2B_PANEL_URL in .env (e.g. http://10.8.0.9:3000)"

  cat >"$INSTALL_DIR/config/worker.toml" <<EOF
# generated by bootstrap-worker.sh — Author: kejiqing
# coord: e2bserver @ passionke/deploy-all-in-one
# stable settings sourced from .env; re-run with a new tag to upgrade
worker_token = "$E2B_WORKER_TOKEN"
panel_url = "$E2B_PANEL_URL"
worker_addr = "$WORKER_ADDR"
advertise_host = "${E2B_ADVERTISE_HOST:-}"
max_sandboxes = ${E2B_MAX_SANDBOXES:-4}
data_dir = "$INSTALL_DIR/data"
heartbeat_interval_secs = 15
container_runtime = "$RUNTIME"
health_wait_timeout_secs = 30
traffic_ports = [3000, 7681, 8080]

[nas]
server = "nfs.supone.top"
export = "/mnt/NAS0/nfs-export"
host_mount_root = "${E2B_NAS_HOST_MOUNT_ROOT:-}"
nfs_version = "3"
sandbox_inject = "bind"
mount_options_linux = "vers=3,nolock,rw,hard,intr"
EOF
  chmod 600 "$INSTALL_DIR/config/worker.toml"
  echo "==> config $INSTALL_DIR/config/worker.toml"
}

start_worker() {
  pkill -f "$INSTALL_DIR/bin/e2b-worker run" 2>/dev/null || true
  sleep 1
  nohup env E2B_WORKER_CONFIG="$INSTALL_DIR/config/worker.toml" \
    "$INSTALL_DIR/bin/e2b-worker" run >>"$INSTALL_DIR/e2b-worker.log" 2>&1 &
  echo "==> e2b-worker pid=$! log=$INSTALL_DIR/e2b-worker.log"
}

verify() {
  sleep 2
  local host="${WORKER_ADDR%:*}" port="${WORKER_ADDR##*:}"
  [[ "$host" == "0.0.0.0" ]] && host="127.0.0.1"
  curl -sf -H "X-Worker-Token: $E2B_WORKER_TOKEN" \
    "http://${host}:${port}/internal/v1/health" | python3 -m json.tool \
    || die "worker health check failed — see $INSTALL_DIR/e2b-worker.log"
}

usage() {
  cat <<'EOF'
Usage: bash bootstrap-worker.sh <release-tag>

  Stable settings: .env in cwd or next to this script
    E2B_PANEL_URL=...
    E2B_WORKER_TOKEN=...
    E2B_ADVERTISE_HOST=...

  Example:
    bash bootstrap-worker.sh release-v1.0.1
EOF
}

main() {
  if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
  fi

  require_cmd curl
  require_cmd "$RUNTIME"

  local tag
  tag="$(resolve_image_tag "${1:-}")"

  echo "==> coord: e2bserver"
  echo "==> install dir: $INSTALL_DIR"
  echo "==> image tag: $tag (ACR_REGISTRY=$ACR_REGISTRY)"

  pull_and_extract "$tag"
  pull_base "$tag"
  write_config
  start_worker
  verify

  echo ""
  echo "worker ready (coord e2bserver)."
  echo "  registers with Panel at $E2B_PANEL_URL"
}

main "$@"
