#!/usr/bin/env bash
# Panel 节点一键部署：全部从 ACR 拉取，无需业务仓 git — Author: kejiqing
#
# 项目坐标：e2bserver（公开仓 passionke/deploy-all-in-one）
#
#   curl -fsSL https://raw.githubusercontent.com/passionke/deploy-all-in-one/main/e2bserver/bootstrap-panel.sh \
#     -o bootstrap-panel.sh
#   E2B_IMAGE_TAG=release-v1.0.1 bash bootstrap-panel.sh
#
# Env:
#   E2B_IMAGE_TAG          必填推荐：release-v1.0.1（与发版 tag 一致）
#   E2B_INSTALL_DIR        默认 /opt/e2bserver
#   E2B_CONTAINER_RUNTIME  podman|docker，默认 podman
#   E2B_SANDBOX_DOMAIN     默认 supone.top
#   E2B_WORKER_TOKEN       可选；不设则生成并写入 config/.worker-token
#   ACR_REGISTRY / ACR_USERNAME / ACR_PASSWORD  私有仓时需要
set -euo pipefail

RUNTIME="${E2B_CONTAINER_RUNTIME:-podman}"
export E2B_CONTAINER_RUNTIME="$RUNTIME"
INSTALL_DIR="${E2B_INSTALL_DIR:-/opt/e2bserver}"
SANDBOX_DOMAIN="${E2B_SANDBOX_DOMAIN:-supone.top}"
TOKEN_FILE="$INSTALL_DIR/config/.worker-token"
PANEL_CONFIG="$INSTALL_DIR/config/deploy.toml"
PANEL_LOG="$INSTALL_DIR/e2bserver.log"
ACR_REGISTRY="${ACR_REGISTRY:-crpi-cf9vxpq3n8or17mw.cn-hangzhou.personal.cr.aliyuncs.com/passionke}"

die() { echo "error: $*" >&2; exit 1; }

if [[ "$(uname -s)" == "Darwin" ]]; then
  die "macOS cannot use ACR Linux binary — run on a Linux Panel host"
fi

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing command: $1"
}

detect_arch_tag() {
  case "$(uname -m)" in
    x86_64) echo amd64 ;;
    aarch64|arm64) echo arm64 ;;
    *) die "unsupported arch: $(uname -m)" ;;
  esac
}

image_tag() {
  if [[ -n "${E2B_IMAGE_TAG:-}" ]]; then
    echo "$E2B_IMAGE_TAG"
  else
    detect_arch_tag
  fi
}

acr_login_if_needed() {
  local host="${ACR_REGISTRY%%/*}" user="${ACR_USERNAME:-${ACR_USER:-}}"
  if [[ -n "$user" && -n "${ACR_PASSWORD:-}" ]]; then
    echo "$ACR_PASSWORD" | "$RUNTIME" login "$host" -u "$user" --password-stdin
  fi
}

pull_and_extract() {
  local tag ref cid
  tag="$(image_tag)"
  ref="${ACR_REGISTRY%/}/e2b-binaries:${tag}"
  echo "==> pull $ref"
  acr_login_if_needed
  "$RUNTIME" pull "$ref" || die "failed to pull $ref — wait for release CI / check tag"

  mkdir -p "$INSTALL_DIR/bin" "$INSTALL_DIR/config" "$INSTALL_DIR/data"
  cid="$("$RUNTIME" create "$ref")"
  "$RUNTIME" cp "$cid:/opt/e2b/bin/e2bserver" "$INSTALL_DIR/bin/e2bserver"
  "$RUNTIME" cp "$cid:/opt/e2b/bin/e2b-worker" "$INSTALL_DIR/bin/e2b-worker" 2>/dev/null || true
  "$RUNTIME" rm "$cid" >/dev/null
  chmod 755 "$INSTALL_DIR/bin/e2bserver"
  [[ -f "$INSTALL_DIR/bin/e2b-worker" ]] && chmod 755 "$INSTALL_DIR/bin/e2b-worker"
  echo "==> installed $INSTALL_DIR/bin/e2bserver"
}

pull_base() {
  local tag ref
  tag="$(image_tag)"
  ref="${ACR_REGISTRY%/}/e2b-base:${tag}"
  echo "==> pull $ref"
  acr_login_if_needed
  "$RUNTIME" pull "$ref" || die "failed to pull $ref"
  "$RUNTIME" tag "$ref" e2b-base:latest
  echo "==> e2b-base:latest ← $ref"
}

worker_token() {
  if [[ -n "${E2B_WORKER_TOKEN:-}" ]]; then
    echo "$E2B_WORKER_TOKEN"
    return
  fi
  if [[ -f "$TOKEN_FILE" ]]; then
    cat "$TOKEN_FILE"
    return
  fi
  local token="e2b_wk_$(openssl rand -hex 16 2>/dev/null || date +%s)"
  mkdir -p "$(dirname "$TOKEN_FILE")"
  printf '%s' "$token" >"$TOKEN_FILE"
  chmod 600 "$TOKEN_FILE"
  echo "$token"
}

write_config() {
  local token="$1"
  cat >"$PANEL_CONFIG" <<EOF
# generated by bootstrap-panel.sh — Author: kejiqing
api_key = "e2b_53ae1fed82754c17ad8077fbc8bcdd90"
api_addr = "0.0.0.0:3000"
proxy_addr = "0.0.0.0:3002"
traffic_addr = "0.0.0.0:3001"
sandbox_domain = "$SANDBOX_DOMAIN"
traffic_ports = [3000, 7681, 8080]
admin_auth = false
data_dir = "$INSTALL_DIR/data"
container_runtime = "$RUNTIME"
default_timeout_secs = 300
base_image = "e2b-base:latest"
envd_version = "0.1.3"
health_wait_timeout_secs = 30

[cluster]
enabled = true
worker_token = "$token"

[nas]
server = "nfs.supone.top"
export = "/mnt/NAS0/nfs-export"
host_mount_root = "/mnt/nas0"
nfs_version = "3"
sandbox_inject = "bind"
mount_options_linux = "vers=3,nolock,rw,hard,intr"

[templates_ci]
enabled = false
acr_registry = "${ACR_REGISTRY}"
image_repo = "e2b-templates"
github_repo = "passionke/e2bserver"
workflow_file = "template-build.yml"
git_ref = "main"
ci_token = ""
github_token = ""
panel_public_url = ""
oss_endpoint = ""
oss_bucket = ""
oss_access_key_id = ""
oss_access_key_secret = ""
oss_context_prefix = "template-builds"
oss_download_url_secs = 86400
oss_context_ttl_days = 30
EOF
  chmod 600 "$PANEL_CONFIG"
  echo "==> config $PANEL_CONFIG"
}

start_panel() {
  pkill -f "$INSTALL_DIR/bin/e2bserver run" 2>/dev/null || true
  # also catch older absolute/relative paths
  pkill -f "e2bserver run" 2>/dev/null || true
  sleep 1
  nohup env E2B_CONFIG="$PANEL_CONFIG" \
    "$INSTALL_DIR/bin/e2bserver" run >>"$PANEL_LOG" 2>&1 &
  local pid=$!
  echo "==> e2bserver pid=$pid log=$PANEL_LOG"

  local i
  for i in $(seq 1 40); do
    if curl -sf http://127.0.0.1:3000/healthz >/dev/null 2>&1; then
      echo "==> healthz ok"
      return 0
    fi
    sleep 0.5
    kill -0 "$pid" 2>/dev/null || { echo "panel exited — see $PANEL_LOG"; tail -30 "$PANEL_LOG" >&2; exit 1; }
  done
  die "healthz timeout — see $PANEL_LOG"
}

main() {
  require_cmd curl
  require_cmd "$RUNTIME"
  [[ -n "${E2B_IMAGE_TAG:-}" ]] || echo "==> warning: E2B_IMAGE_TAG unset, using arch tag $(detect_arch_tag)"

  echo "==> install dir: $INSTALL_DIR"
  echo "==> image tag: $(image_tag) (ACR_REGISTRY=$ACR_REGISTRY)"

  pull_and_extract
  pull_base

  local token
  token="$(worker_token)"
  # persist if generated via env
  if [[ ! -f "$TOKEN_FILE" ]]; then
    printf '%s' "$token" >"$TOKEN_FILE"
    chmod 600 "$TOKEN_FILE"
  fi
  write_config "$token"
  start_panel

  echo ""
  echo "panel ready."
  echo "  admin:  http://127.0.0.1:3000/admin"
  echo "  config: $PANEL_CONFIG"
  echo "  worker token file: $TOKEN_FILE"
  echo "  worker token:      $token"
  echo ""
  echo "next (Worker host — coord e2bserver):"
  echo "  curl -fsSL https://raw.githubusercontent.com/passionke/deploy-all-in-one/main/e2bserver/bootstrap-worker.sh -o bootstrap-worker.sh"
  echo "  E2B_IMAGE_TAG=$(image_tag) E2B_PANEL_URL='http://<panel-ip>:3000' \\"
  echo "    E2B_WORKER_TOKEN='$token' E2B_ADVERTISE_HOST='<worker-ip>' \\"
  echo "    bash bootstrap-worker.sh"
}

main "$@"
